;;(load "eshell-auto")

;; Set these variables via custom
(custom-set-variables
 '(require-final-newline nil)
 '(modeline-click-swaps-buffers t)
 '(auto-save-timeout 960 t)
 '(next-line-add-newlines nil)
 '(compilation-error-regexp-systems-list (quote (gnu comma)))
 '(gnus-use-cache t)
 '(gnus-suppress-duplicates t)
 '(c-macro-preprocessor "gcc -C -E -")
 '(column-number-mode t)
 '(gnus-novice-user nil)
 '(compilation-mouse-motion-initiate-parsing t)
 '(resize-minibuffer-frame-exactly t)
 '(c-hanging-comment-ender-p nil)
 '(c-indent-comments-syntactically-p t)
 '(c-macro-prompt-flag t)
 '(shell-multiple-shells t)
 '(balloon-help-background "LightYellow")
 '(bbdb-use-pop-up nil)
 '(explicit-shell-file-name shell-file-name)
 '(truncate-lines nil)
 '(query-replace-highlight t)
 '(line-number-mode t)
 '(enable-local-eval t)
 '(user-full-name "Vin Shelton" t)
 '(mail-user-agent (quote message-user-agent))
 '(mouse-yank-at-point nil)
 '(find-file-compare-truenames t)
 '(shell-file-name "zsh")
 '(gnuserv-frame (quote gnuserv-visible-frame-function))
 '(gnus-expert-user t)
 '(user-mail-address "acs@xemacs.org" t)
 '(query-user-mail-address nil)
 '(*try-oblique-before-italic-fonts* t)
 '(indent-tabs-mode t)
 '(eshell-modules-list (quote (eshell-alias eshell-banner eshell-basic
eshell-cmpl eshell-dirs eshell-glob eshell-hist eshell-ls eshell-pred
eshell-prompt eshell-rebind eshell-script eshell-term eshell-unix))))
(custom-set-faces)
