#!/bin/bash

# Customize a VM, whether it is debian-based or Fedora-based.

# External variables that might be overridden in the environment.
# The following defaults work from a Windows host.
# In order to install from my linux host at home:
# hosthome=/media/sf_host-home/acs ZIPROOT=/media/sf_host-SSD-2TB/opt/zip Build_VM
: ${htag:=host-root}
: ${hosthome:=/media/sf_${htag}/cygwin64/home/shelta}
: ${variable_source:=${SCMROOT}/acsfiles/system}
: ${USRLOCAL:=/opt}
: ${SCMROOT:=${HOME}/scmroot}
: ${ZIPROOT:=${hosthome}/software/zip}
export SCMROOT USRLOCAL ZIPROOT

# Define a function to install packages on either debian or Fedora.
function install_package() {
  if [[ -x /usr/bin/dnf ]]; then
    pm="dnf --assumeyes"
  elif [[ -x /usr/bin/apt-get ]]; then
    pm="apt-get --yes"
  else
    echo Neither dnf nor apt-get was found to install packages.  Exiting. >/dev/tty
    exit 3
  fi
  sudo ${pm} install $*
}

# Define a function to upgrade packages on either debian or Fedora.
function upgrade_packages() {
  if [[ -x /usr/bin/dnf ]]; then
    sudo dnf --assumeyes upgrade
  elif [[ -x /usr/bin/apt-get ]]; then
    sudo apt-get --yes update && sudo apt-get --yes upgrade
  else
    echo Neither dnf nor apt-get was found to upgrade packages.  Exiting. >/dev/tty
    exit 3
  fi
}

# If sudo isn't installed (as on debian), first
# use su to ensure that sudo is installed
# and that we are authorized to use it.
if [[ ! -x /usr/bin/sudo ]]; then
  su -c "apt-get install sudo;
         usermod --append --groups sudo acs;
         sync;
         reboot" root
fi

# First time through: install VirtualBox Guest additions,
# upgrade packages and reboot.
if ! groups acs | grep vboxsf >/dev/null; then
  if ! sudo mount /dev/cdrom /mnt ; then
    echo "Insert the Guest Additions CD image and press Enter" >/dev/tty
    read junk
    if ! sudo mount /dev/cdrom /mnt ; then
      echo "Could not mount the Guest Additions CD" >/dev/tty
      exit 1
    fi
  fi

  if [[ ! -x /mnt/VBoxLinuxAdditions.run ]]; then
    echo "Cannot find /mnt/VBoxLinuxAdditions.run, exiting." >/dev/tty
    exit 2
  fi

  install_package gcc make
  install_package linux-headers-amd64 || install_package kernel-headers
  sudo /mnt/VBoxLinuxAdditions.run
  sudo usermod --append --groups vboxsf acs

  # Do the package upgrade here, after installing
  # the VirtualBox Guest Additions.
  upgrade_packages

  sync
  sudo reboot
fi

if [[ -x /usr/bin/apt-get ]]; then
  variable_source=${variable_source}/debian
elif [[ -x /usr/bin/dnf ]]; then
  variable_source=${variable_source}/Fedora
else
  echo Cannot ascertain whether this system is debian or Fedora >/dev/tty
  exit 1
fi

# Configure my home directory.
mkdir -p ${SCMROOT}/hgroot
tar cf - -C ${hosthome}/scmroot/hgroot acsfiles | tar xf - -C ${SCMROOT}/hgroot
ln -s hgroot/acsfiles hgroot/acsfiles/binfiles hgroot/acsfiles/rcfiles ${SCMROOT}
(
  cd
  ${SCMROOT}/binfiles/LinkStartupFiles
  mkdir .hist
  tar xf ${ZIPROOT}/wp.tar
)

# Make the USRLOCAL hierarchy.
sudo chown acs ${USRLOCAL}
mkdir ${USRLOCAL}/{bin,build,include,lib,share,src}

# Set up the execution path.
PATH=${HOME}/bin:${USRLOCAL}/bin:$PATH

# Install zshell, source control systems and the i3 window manager.
install_package zsh
if [[ -d /etc/zsh ]]; then
  sudo mv /etc/zsh /etc/ZSH-dist
else
  sudo mkdir /etc/ZSH-dist
  sudo mv /etc/z* /etc/ZSH-dist
fi
install_package git i3 mercurial

. ${variable_source}/Microsoft_fonts

# Unpack ubuntu fonts and update the font cache.
sudo -s <<EOF
  cd /usr/share/fonts
  [[ -d truetype ]] && cd truetype
  unzip ${ZIPROOT}/ubuntu-font-family-0.83.zip
  fc-cache -f -v
EOF

# Define a function to clone a git repo.
function clone_git_repo() {
  # $1 - name of git repo (i.e. emacs)
  # $2 - URL of repo
  local nickname=$1
  local repo_url=$2

  mkdir -p ${SCMROOT}/gitroot
  (
    cd ${SCMROOT}/gitroot

    git clone ${repo_url} ${nickname}
    touch --date=2016-01-01 ${nickname}/last_update
    cd ..
    ln -s gitroot/${nickname}
  )
}

# Define a function to link the most recent version
# of an application into the ${USRLOCAL} hierarchy.
function link_latest() {
  # $1 - destination name, i.e. "emacs"
  # $2 - source name, i.e. "emacs-2016-01-02"
  local nickname=$1
  local fullname=$2
  (
    cd ${USRLOCAL}
    ln -s ${fullname} ${nickname}
    cd bin
    ln -s ../${nickname}/bin/* .
  )
}

typeset -A repos
repos["conky"]="https://github.com/brndnmtthws/conky.git"
repos["emacs"]="git://git.savannah.gnu.org/emacs.git"
repos["zsh"]="git://git.code.sf.net/p/zsh/code"

. ${variable_source}/packages_required

# Build and install conky because my conky configuration
# crashes the default conky.
pname=conky
clone_git_repo ${pname} ${repos[$pname]}
install_package ${deps[$pname]}
mk-${pname}

# Build and install zsh.
pname=zsh
clone_git_repo ${pname} ${repos[$pname]}
install_package ${deps[$pname]}
CFLAGS=-O update-${pname}
link_latest ${pname} ${pname}-$(today)
[[ -x ${USRLOCAL}/bin/${pname} ]] && sudo usermod --shell ${USRLOCAL}/bin/${pname} acs

# Build and install emacs.
pname=emacs
clone_git_repo ${pname} ${repos[$pname]}
install_package ${deps[$pname]}
mk-${pname}
link_latest ${pname} ${pname}-$(today)

echo "
*********************************
Remember to:
  1. Turn off screensaver.
  2. Create ~/bin/xfce-autostart.
  3. Modify session start-up.
  4. Tune up xfce window manager.
*********************************
"

# Local Variables:
# mode: shell-script
# sh-basic-offset: 2
# sh-indentation: 2
# indent-tabs-mode: nil
# End:
