#!/bin/bash

# Bring a Sparky 4.6 CLI installation up to date.
# This script is run as root.

# Install some packages.
apt-get update
apt-get dist-upgrade
apt-get install sudo nfs-kernel-server ssh devscripts build-essential

# Install powernap for power management.
#   https://ubuntuforums.org/showthread.php?t=2045541
#   https://bugs.launchpad.net/powernap/+bug/1497782

# Install powernap; get and install -common first.
: ${pkg_server:="http://mirrors.kernel.org/ubuntu/pool/main/p/powernap"}
: ${pn_ver:="2.21-0ubuntu1_all"}
for p in powernap-common powernap; do
  pw=${p}_${pn_ver}.deb
  wget $pkg_server/$pw
  dpkg --install ./$pw
done

# Patch powernap.
patch /usr/share/pyshared/powernap/monitors/ConsoleMonitor.py <<EOF
--- ConsoleMonitor.py.orig	2012-05-18 15:06:44.000000000 -0400
+++ ConsoleMonitor.py	2017-06-29 07:57:41.873755139 -0400
@@ -38,6 +38,7 @@
         if source == "i8042" or source == "keyboard" or source == "mouse":
             items.pop(0)
             items.pop()
+            items.pop()
             for i in items:
                 interrupts += int(i)
     f.close()

EOF
rm /usr/lib/python2.7/dist-packages/powernap/monitors/ConsoleMonitor.pyc

# Configure powernap.
patch /etc/powernap/config <<EOF
--- config.orig	2017-06-29 15:18:05.306873456 -0400
+++ config	2017-06-29 15:31:40.907043551 -0400
@@ -93,7 +93,7 @@
 # STAGE2_ACTION_METHOD is set correctly.
 # Example:
 #   STAGE2_ABSENT_SECONDS = 500
-STAGE2_ABSENT_SECONDS = 0
+STAGE2_ABSENT_SECONDS = 480
 
 # The STAGE2_ACTION_METHOD variable determines what action should be taken
 # after a period on inactivity while under PowerSave Mode (See ACTION_METHOD
@@ -106,7 +106,7 @@
 # The default mode of operation is best-effort. This method will try to
 # user-defined script  at "/etc/powernap/action", or suspend, hibernate,
 # or poweroff the machine.
-STAGE2_ACTION_METHOD = 4
+STAGE2_ACTION_METHOD = 1
 
 ############################################################################
 ####                          MONITORS                                  ####
@@ -144,6 +144,8 @@
 #  sshd = "sshd: .*\[priv\]$"
 #  kvm = "kvm "
 [ProcessMonitor]
+dpkg = "dpkg "
+aptget = "apt-get "
 #init = "^/sbin/init"
 
 # The [LoadMonitor] section defines the load threshold.  When the system load
@@ -172,7 +174,7 @@
 #  https = 443
 #  other = 64500-65000
 [TCPMonitor]
-#ssh = 22
+ssh = 22
 
 # The [UDPMonitor] section lists all the UDP ports on which to listen
 # for data.
EOF

# Configure rc.local.
patch /etc/rc.local <<EOF
--- rc.local.orig	2017-06-29 12:45:13.293964958 -0400
+++ rc.local	2017-06-29 12:25:32.466140856 -0400
@@ -11,4 +11,8 @@
 #
 # By default this script does nothing.
 
+fstrim --all
+
+powernapd
+
 exit 0
EOF

# Local Variables:
# mode: shell-script
# sh-basic-offset: 2
# sh-indentation: 2
# indent-tabs-mode: nil
# End:
