;(message "Entering acs-custom.el")

;; Set these variables via custom
(custom-set-variables
 '(auto-save-timeout 960 t)
 '(bar-cursor nil)
 '(bbdb-use-pop-up nil)
 '(buffers-menu-grouping-function nil)
 '(buffers-menu-max-size 25)
 '(buffers-menu-sort-function nil)
 '(buffers-menu-submenus-for-groups-p nil)
 '(build-report-destination '("XEmacs Build Reports List <xemacs-buildreports@xemacs.org>"))
 '(build-report-make-output-files '("mk.out" "check.out" "inst.out"))
 '(c-hanging-comment-ender-p nil)
 '(c-indent-comments-syntactically-p t)
 '(c-macro-preprocessor "gcc -C -E -")
 '(c-macro-prompt-flag t)
 '(column-number-mode t)
 '(compilation-error-regexp-systems-list '(gnu comma))
 '(compilation-mouse-motion-initiate-parsing t)
 '(complex-buffers-menu-p t)
 '(ediff-use-long-help-message nil t)
 '(ediff-window-setup-function 'ediff-setup-windows-plain t)
 '(enable-local-eval t)
 '(eshell-modules-list '(eshell-alias eshell-banner eshell-basic eshell-cmpl eshell-dirs eshell-glob eshell-hist eshell-ls eshell-pred eshell-prompt eshell-rebind eshell-script eshell-term eshell-unix))
 '(find-file-compare-truenames t)
 '(font-menu-ignore-scaled-fonts t)
 '(font-menu-this-frame-only-p t)
 '(gnus-expert-user t)
 '(gnus-novice-user nil)
 '(gnus-suppress-duplicates t)
 '(gnus-use-cache t)
 '(grep-command "egrep -n ")
 '(indent-tabs-mode t)
 '(ispell-program-name "aspell")
 '(line-number-mode t)
 '(load-home-init-file t)
 '(mail-user-agent 'message-user-agent)
 '(minibuffer-confirm-incomplete t)
 '(modeline-click-swaps-buffers t)
 '(mouse-yank-at-point nil)
 '(next-line-add-newlines nil)
 '(patcher-projects '(("packages" "~/cvsroot/xemacs-packages")
		      ("web" "~/cvsroot/xemacsweb")
		      ("build" "~/cvsroot/xemacs-builds")
		      ("21.1" "~/cvsroot/xemacs-21.1")
		      ("21.4" "~/cvsroot/xemacs-21.4")
		      ("21.5" "~/cvsroot/xemacs-21.5")))
 '(query-replace-highlight t)
 '(query-user-mail-address nil)
 '(require-final-newline t)
 '(resize-minibuffer-frame-exactly t)
 '(resize-minibuffer-mode t nil (rsz-minibuf))
 '(shell-multiple-shells t)
 '(tags-build-completion-table 'ask)
 '(teach-extended-commands-p t)
 '(teach-extended-commands-timeout 1)
 '(temp-buffer-show-function 'show-temp-buffer-in-current-frame)
 '(truncate-lines nil)
 '(user-full-name "Vin Shelton" t)
 '(user-mail-address "acs@xemacs.org")
 '(zmacs-regions t))

;(message "Leaving acs-custom.el")
