#!/bin/bash

# If the arch package manager exists, echo its name
# and the options necessary to make it non-interactive.
: ${arch_pm=/usr/bin/pacman}
[[ -x $arch_pm ]] && echo $arch_pm --sync

# Local Variables:
# mode: shell-script
# sh-basic-offset: 2
# sh-indentation: 2
# indent-tabs-mode: nil
# End:
