#!/usr/bin/env zsh

emulate -LR zsh
progname=${0:t}

project=xemacs-21.5
NEW_SCMROOT=/home/acs/tmp
cd $NEW_SCMROOT
hg clone $SCMROOT/$project
cd $project

# Generate list of dates from hg history
# hg history --template "{date|isodate}\n" | col 1 | sort -ur
#dates=( 2012-11-06 2012-09-02 2012-07-02 2012-04-07 2012-01-01 2011-11-02 \
#        2011-09-04 2011-06-01 2011-03-29 2011-01-02 )
#dates=( 2009-01-01 2009-04-01 2009-07-01 2009-10-01 2010-01-01 2010-04-01 \
#        2010-07-05 2010-10-10 2011-01-01 2011-04-02 2011-07-03 2011-10-02 \
#        2012-01-01 2012-04-07 2012-07-02 2012-10-15 )
dates=( 2009-01-01 2009-07-01 2010-01-01 2010-07-05 2011-01-01 2011-04-02 \
        2011-07-03 2011-10-02 2012-01-01 2012-04-07 2012-07-02 2012-10-15 )
for d in $dates; do
  hg update -d $d
  SCMROOT=$NEW_SCMROOT mk-src $project $d
  pushd /opt/src/$project-$d >/dev/null
  ./configure --prefix=/opt \
              --with-cflags="-g -Os -m64 -msse4.2 -ffast-math -fno-exceptions" \
              --with-site-prefixes=/opt --with-infopath=/opt/info \
              --disable-dialogs --disable-widgets --with-sound=native \
              --with-package-path=/opt/site-packages::/opt/xemacs-packages \
              --enable-pdump --enable-bignum=gmp --with-default-eol-detection \
              --enable-mule --without-xim >& conf.out
  make >& mk.out
  make check >& check.out
  popd
  echo
done

# Local Variables:
# mode: shell-script
# sh-indentation: 2
# indent-tabs-mode: nil
# End:
