#!/usr/bin/env zsh

# Remove vestigial XEmacs commands

emulate -LR zsh
progname=${0:t}

OS_dirs=( . )
[[ $(uname -s) == SunOS* ]] && OS_dirs=( ../SunOS-5.5 ../SunOS-5.8 )

cd $USRLOCAL
for d in $OS_dirs; do
  [[ $d != . ]] && echo "\n$d"
  pushd $d/bin
  for f in xem*(@); do
    [[ ! -d ../$f ]] && ls -ld $f && rm $f
  done
  popd
done

# Local Variables:
# mode: shell-script
# sh-indentation: 2
# indent-tabs-mode: nil
# End:
