#!/bin/bash

# Set up default share folders for a VirtualBox VM.

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 <VM_name>"
  exit 1
fi
vm=$1

# Find VirtualBox executable and set the default (linux) paths.
if vbm=$(which VBoxManage 2>/dev/null); then
  host_home=/home/acs
  host_root=/
  host_zip=/opt/zip

  cd ~/VirtualBox\ VMs
# Check for Cygwin (with VBoxManage outside PATH).
else
  PATH="/c/Program Files/Oracle/VirtualBox:$PATH"
  if ! vbm=$(which VBoxManage 2>/dev/null); then
    echo "$0: VBoxManage not found" >&2
    exit 2
  fi
  host_home="$(cygpath -d $HOME)"
  host_root="$(cygpath -d /c)"
  host_zip="$(cygpath -d $ZIPROOT)"

  cd "/c/Users/shelta/Virtualbox VMs"
fi

#echo host_home=\"$host_home\"
#echo host_root=\"$host_root\"
#echo host_zip=\"$host_zip\"

# Various sizes
DISK1=40000
: ${DISK1:=15000}
: ${DISK2:=15000}
: ${MEM:=8192}
: ${VRAM:=64}

"$vbm" createvm --name ${vm} --register --ostype Linux_64
"$vbm" modifyvm        ${vm} --memory ${MEM} --vram ${VRAM} --acpi on --cpus 2
"$vbm" storagectl      ${vm} --name "SATA" --add sata

"$vbm" createmedium disk --filename ${vm}/${vm}1.vdi --size ${DISK1} --variant Fixed
#"$vbm" createmedium disk --filename ${vm}/${vm}2.vdi --size ${DISK2} --variant Fixed
"$vbm" storageattach ${vm} --storagectl "SATA" --device 0 --port 0 --type hdd --medium ${vm}/${vm}1.vdi
#"$vbm" storageattach ${vm} --storagectl "SATA" --device 0 --port 1 --type hdd --medium ${vm}/${vm}2.vdi
"$vbm" storageattach ${vm} --storagectl "SATA" --device 0 --port 1 --type dvddrive --medium emptydrive

"$vbm" sharedfolder add ${vm} --name "host-home" --hostpath "$host_home" --automount
"$vbm" sharedfolder add ${vm} --name "host-root" --hostpath "$host_root" --automount
"$vbm" sharedfolder add ${vm} --name "host-zip"  --hostpath "$host_zip"  --automount

# Local Variables:
# mode: shell-script
# sh-basic-offset: 2
# sh-indentation: 2
# indent-tabs-mode: nil
# End:
