#!/bin/bash

# If the debian package manager exists, echo its name
# and the options necessary to make it non-interactive.
: ${debian_pm=/usr/bin/apt-get}
[[ -x $debian_pm ]] && echo $debian_pm --yes

# Local Variables:
# mode: shell-script
# sh-basic-offset: 2
# sh-indentation: 2
# indent-tabs-mode: nil
# End:
