#!/usr/bin/env zsh

# Run borg backup.

cmd=( borg )
opts=( create --stats --progress --compression auto,zstd --exclude-caches )
[[ -z $repo ]] && repo=/WD-3TB-1/backups/borg

#if [[ ! -d $repo ]]; then
#  print -u2 "$0: Repository $repo does not exist."
#  exit 1
#fi

: {USRLOCAL:=/opt}
: {SRCROOT:=$USRLOCAL/src}
: {ZIPROOT:=$USRLOCAL/zip}

# Key is directory to back up and value is archive name.
typeset -A dirs=(
  $SRCROOT 	src
  $ZIPROOT 	zip
  $HOME    	acs
  /SSD-2/Music	Music
)

for d in ${(k)dirs}; do
  ${cmd} ${opts} --exclude $SCMROOT --exclude "$HOME/.cache/*" ${repo}::${dirs[$d]}-$(today) $d
done

# Local Variables:
# mode: shell-script
# sh-indentation: 2
# indent-tabs-mode: nil
# End:
