#!/usr/bin/env zsh

# Run obnam backup
setopt extended_glob

# Include home directory and all of /raid-3tb except these sub-directories:
#exceptions=(Attic
#            CygwinKit
#            Videos
#            backups
#            lost+found
#            opt)

#exceptions=( /raid-3tb/${^exceptions} )

exceptions=(backups
            lost+found
            opt)
exceptions=( /SSD-2TB/${^exceptions} )

# Parse arguments into obnam options and directories
ob_opts=()
while [[ $# -gt 0 && $1 = -* ]]; do
  if [[ $1 == -- ]]; then
    shift
    break
  fi
  ob_opts+="$1"
  shift
done

# Should we backup /opt/src? /etc?
# If so, just add those paths to the command line
for repo in /SSD-2TB/backups/obnam-backup /media/acs/5ac9e345-ab80-4fb4-b5e7-041bec76829d/obnam-backup; do
  set -x
  obnam --repository="$repo" $ob_opts backup $HOME /SSD-2TB/*~${(j:~:)~exceptions} $*
  set +x
done

print -r "Also (if you want to be complete):"
print -r obnam -r sftp://acs@legolas/WD-4TB-1/obnam-backups $ob_opts backup $HOME /SSD-2TB/*~${(j:~:)~exceptions} $*


# Local Variables:
# mode: shell-script
# sh-indentation: 2
# indent-tabs-mode: nil
# End:
