#!/bin/bash

# If the fedora package manager exists, echo its name
# and the options necessary to make it non-interactive.
: ${fedora_pm=/usr/bin/dnf}
[[ -x $fedora_pm ]] && echo $fedora_pm --assumeyes

# Local Variables:
# mode: shell-script
# sh-basic-offset: 2
# sh-indentation: 2
# indent-tabs-mode: nil
# End:
