#!/usr/bin/env zsh

# Print the names of all the files in the current hierarchy
# newer than the specified file, omitting source code repository
# maintenance files.

local progname=${0:t}

if (( $# != 1 )); then
  print -u2 "usage: $progname reference_file"
  return 1
fi

find . -type f -not -path '*/CVS/*' -not -path '*/.hg*' -not -path '*/.git/*' -newer $1 -print 2>/dev/null

# Local Variables:
# mode: shell-script
# sh-indentation: 2
# indent-tabs-mode: nil
# End:
