#!/bin/sh

# Fetch all the XEmacs mailing list archives for the specified months
# Usage: get-xemacs-ml <yyyymm> [yyyym2...]
 
# Execute this script under the Z shell
[ ! -n "$ZSH_VERSION" ] && exec zsh "$0" ${1+"$@"}

progname=${0:t}

aroot="http://calypso.tux.org/pipermail"
names=(January February March April May June July August September October November December)

foreach date
  year=${date%??}
  mndx=${date#????}
  month=${names[$mndx]}
  list=xemacs-review
  wget -O $list.$date.gz --http-user=xemacs-review --http-passwd=review-xemacs $aroot/$list/$year-$month.txt.gz
  gunzip $list.$date.gz || rm $list.$date.gz
  list=xemacs-design
  wget -O $list.$date.gz $aroot/$list/$year-$month.txt.gz
  gunzip $list.$date.gz || rm $list.$date.gz
  list=xemacs-patches
  wget -O $list.$date.gz $aroot/$list/$year-$month.txt.gz
  gunzip $list.$date.gz || rm $list.$date.gz
end

# Local Variables:
# mode: shell-script
# sh-indentation: 2
# indent-tabs-mode: nil
# End:
