#!/bin/bash

# Script to start up an i3 session.

: ${USRLOCAL:=/opt}
PATH=$HOME/bin:$USRLOCAL/bin:$PATH

compton &

my_conky

# clementine &
emacs -f about-emacs &

# The browser is passed as the first parameter
$1 &

# The terminal is passed as the second parameter
#export TERMINAL=$2
#[[ $TERMINAL == tilix ]] && source /etc/profile.d/vte-2.91.sh
#i3-sensible-terminal --title=zsh &

# Local Variables:
# mode: shell-script
# sh-basic-offset: 2
# sh-indentation: 2
# indent-tabs-mode: nil
# End:
