#!/bin/sh

# Configure and install scripts on the local machine.

dflt="/usr/local"
echo "Default prefix for installing packages [$dflt]:\c"
read prefix
prefix="${prefix:-$dflt}"

destdir="$1"
shift

mkdir -p "$destdir" 2>/dev/null

for f in "$@"
do
  perl -pe "s@USRLOCAL@$prefix@g" <$f >$destdir/$f
  chmod 755 $destdir/$f
done
