#!/bin/bash

# Link my startup files.

[[ -z $OSTYPE ]] && OSTYPE=linux
[[ $OSTYPE == *linux* ]] && OSTYPE=linux
[[ $OSTYPE == *ygwin* ]] && OSTYPE=NT

LINK="ln -s"

while read linkname src targetOS
do
  #echo "linkname = $linkname; src = $src; OS = $targetOS"
  if [[ $targetOS == *$OSTYPE* ]]; then
    mkdir -p $(dirname $linkname)
    (
      src=$(eval echo $src)
      ${LINK} $src $linkname
    )
  fi
done < $SCMROOT/rcfiles/ListOfLinks

# On a Windoze box, the native XEmacs and FSF emacs applications cannot
# read cygwin symbolic links, so copy the customization files.
if [[ $OSTYPE == NT ]]; then
  harden_list=(
    .emacs
    lib/lisp/{fsf,xemacs}/{acs-custom,default}.el
    lib/lisp/detached-minibuf.el
    lib/lisp/fsf/mic-paren.el
  )

# These files change from system to system.
else
  harden_list=(
    .conky.hostname
    .conky.status
    bin/i3-autostart
    bin/xfce-autostart
    .i3/config
    lib/lisp/fsf/acs-custom.el
  )
fi

# harden_list is the list of symbolic links to
# 'break' by copying the contents.
for f in ${harden_list[*]}; do
  t=$(readlink $f)
  rm $f
  cp $t $f
done

# Local Variables:
# mode: shell-script
# sh-indentation: 2
# indent-tabs-mode: nil
# End:
