#!/usr/bin/env zsh

# Make a specified symlink point to the latest version of that thing
# Usage: link_latest <package>
#        ie: link_latest xemacs-packages

emulate -LR zsh
progname=${0:t}

(( ARGC == 0 )) && print -u2 "Usage: $progname linkname" && return 1

package=$1
rm $package || return $?
ln -s ${package}*(oc[1]) $package

# Local Variables:
# mode: shell-script
# sh-indentation: 2
# indent-tabs-mode: nil
# End:
