#!/bin/bash

# Link my startup files.

: ${progname:=$(basename $0)}

[[ -z $OSTYPE ]] && OSTYPE=linux
[[ $OSTYPE == *linux* ]] && OSTYPE=linux
[[ $OSTYPE == *ygwin* ]] && OSTYPE=NT

#LINK="ln -s"
LINK=cp

while read linkname src targetOS
do
  #echo "linkname = $linkname; src = $src; OS = $targetOS"
  if [[ $targetOS == *$OSTYPE* ]]; then
    mkdir -p $(dirname $linkname)
    (
      src=$(eval echo $src)
      ${=LINK} $src $linkname
    )
  fi
done < $SCMROOT/rcfiles/ListOfLinks

# On a Windoze box, the native XEmacs and FSF emacs applications
# cannot read cygwin symbolic links, so hard-copy the files.
if [[ $OSTYPE == NT ]]; then
  for f in .emacs lib/lisp/{fsf,xemacs}/{acs-custom,default}.el lib/lisp/detached-minibuf.el lib/lisp/fsf/mic-paren.el; do
    t=$(readlink $f)
    rm $f
    cp $t $f
  done
fi

# Local Variables:
# mode: shell-script
# sh-indentation: 2
# indent-tabs-mode: nil
# End:
