#!/usr/bin/env zsh

# Loop a command several times until the command passes,
# or until a maximum number of loops has expired.

emulate -LR zsh

: ${maxloops:=25}
: ${sleep_period:=10}

for (( i=0; i < maxloops; i++ ))
do
  $*
  retcode=$?
  (( retcode == 0 )) && break
  sleep $sleep_period
done

(( i == maxloops )) && print -u2 "$0: \'$*\' returned non-zero values $maxloops times"
exit $retcode

# Local Variables:
# mode: ksh
# sh-indentation: 2
# indent-tabs-mode: nil
# End:
