#!/usr/bin/env zsh

# Loop a command several times until the command passes,
# or until a maximum number of loops has expired.

emulate -LR zsh
progname=${0:t}

: ${maxloops:=25}
: ${sleep_period:=10}
: ${errfile:=/tmp/acs-$progname.$$}

for (( i=0; i < maxloops; i++ ))
do
  $*
  retcode=$?
  (( retcode == 0 )) && break
  sleep $sleep_period
done >& $errfile

(( i == maxloops )) && print -u2 "$progname: \'$*\' returned non-zero values $maxloops times;
for details, see $errfile"
exit $retcode

# Local Variables:
# mode: ksh
# sh-indentation: 2
# indent-tabs-mode: nil
# End:
