#!/usr/bin/env zsh

# Copy the conky configuration from source code control
# and set the color of the status line.

color1="FFA300"
case $(xfconf-query --channel xfce4-desktop --property /backdrop/screen0/monitor0/workspace0/last-image ) in
  (*LakePowell*)
    color1="NavyBlue"
    ;;

  # Old man in China
  (*lSed5VXIQnOw7PMfB9ht_IMG_1642*)
    color1="LightYellow"
    ;;

  # VW Bus
  (*unsplash_52d5c05422a47_1*)
    color1="LightYellow"
    ;;

  # Paris
  (*paris-motionbug*)
    color1="LightYellow"
    ;;

  # Traffuc
  (*mtNrf7oxS4uSxTzMBWfQ_DSC_0043*)
    color1="LightYellow"
    ;;
esac

cd ~
rm .conkyrc
sed -e "s/color1 = 'FFA300',/color1 = '$color1',/" < $SCMROOT/acsfiles/rcfiles/conkyrc > .conkyrc

# Local Variables:
# mode: shell-script
# sh-basic-offset: 2
# sh-indentation: 2
# indent-tabs-mode: nil
# End:
