#!/bin/sh
#
# Make and install a version of bzip
# Options:
#   -u Unpack the sources from tarfiles
 
# Execute this script under the Z shell
[ ! -n "$ZSH_VERSION" ] && exec zsh "$0" ${1+"$@"}

progname=${0:t}

prefix=${USRLOCAL:-/usr/local}
jobs=
unpack=

err=1
while getopts ":ru" opt
do
  case $opt in
  (u)	unpack=-u
	;;
  # Unknown option
  (?)	print -u2 "$progname: invalid option: $argv[$OPTIND]"
	exit $err
	;;
  esac
done

shift $OPTIND-1			# Skip over options

pkgsrc=$(getsource $unpack bzip2)
mkdir $pkgsrc:t
pushd $pkgsrc:t
symlink-tree $(relative $pkgsrc)
make
make PREFIX=$prefix install
popd
