#!/usr/bin/env zsh

# Build latest conky from git
emulate -LR zsh
progname=${0:t}

: ${USRLOCAL:=/usr/local}
: ${BLDROOT:=$USRLOCAL/build}

project=conky

scm_update $project
s=$(mk-src $project)
b=$BLDROOT/${s:t}
mkdir $b
cd $b

cmake -DCMAKE_INSTALL_PREFIX=$USRLOCAL -DBUILD_XDBE=true $s
make install

# Local Variables:
# mode: shell-script
# sh-indentation: 2
# indent-tabs-mode: nil
# End:
