#!/usr/bin/env zsh

# Build latest exa from git
emulate -LR zsh
progname=${0:t}

: ${USRLOCAL:=/usr/local}
: ${BLDROOT:=$USRLOCAL/build}

project=exa

install=
zparseopts -D i=install -install=install
cd $(GetSource --src=$BLDROOT --update $project)

make PREFIX=$USRLOCAL
[[ -n $install ]] && make PREFIX=$USRLOCAL install

# Local Variables:
# mode: shell-script
# sh-basic-offset: 2
# sh-indentation: 2
# indent-tabs-mode: nil
# End:
