#!/usr/bin/env zsh

# Make and install versions of zlib and libpng

emulate -LR zsh

progname=${0:t}
CC=${CC:-gcc}

: ${USRLOCAL:=/usr/local}
: ${BLDROOT:=$USRLOCAL/build}
: ${SRCROOT:=$USRLOCAL/src}
: ${ZIPROOT:=$USRLOCAL/zip}

# Halt on an error unpacking or building either zlib or libpng
set -e

zlibsrc=$(unpack zlib)
bld -ltki $(relative $zlibsrc)

pngsrc=$(unpack libpng)
CPPFLAGS=-I$USRLOCAL/include LDFLAGS=-L$USRLOCAL/lib bld -ci $(relative $pngsrc)

# Local Variables:
# mode: shell-script
# sh-indentation: 2
# indent-tabs-mode: nil
# End:
