#!/bin/sh

# Make a source tree from the CVS sources of the specified project.
 
# Execute this script under the Z shell
[ ! -n "$ZSH_VERSION" ] && exec zsh "$0" ${1+"$@"}

set -e		# Exit at the first sign of trouble.

cmdname="${0:t}"

case $# in
  1)	PROJECT="$1"
	;;
  2)	PROJECT="$1"
	VERSION="$2"
	;;
  0|*)	print -u2 "Usage: $cmdname <project> [version]"
	exit 1;
	;;
esac

# If no other version name was supplied, the default
# version stamp is based on the current date.
VERSION="${VERSION:-$(today)}"

TARGET="$PROJECT-$VERSION"

SRCROOT="${SRCROOT:-${USRLOCAL:-/usr/local}/src}"
SRCDIR="${SRCDIR:-$SRCROOT/$TARGET}"

CVSROOT="${CVSROOT:-$HOME/cvsroot/$PROJECT}"
if [[ ! -d "$CVSROOT" ]]; then
  print -u2 "There is no CVS hierarchy at $CVSROOT".
  exit 2;
fi

mkdir -p "$SRCDIR"
cd "$SRCDIR"

# De-reference symlinks when creating source trees.
# I put this in because emacs now uses the source files
# regex.c and regex.h from the gnulib project
tar cf - -C "$CVSROOT" --exclude CVS --dereference . | tar xf -
