#!/usr/bin/env zsh

# Make a minimal XEmacs suitable for debugging
 
emulate -LR zsh
progname=${0:t}

: ${CC:=gcc}
: ${VERSION:=min}
export CC VERSION

: ${XEMACS:=xemacs-21.5}
CFG_OPTS="--without-x --with-sound=no --with-database=no --without-ldap --without-gpm"
[[ $XEMACS != *21.4* ]] && CFG_OPTS="$CFG_OPTS --disable-kkcc"

source_dir=$(mk-src $XEMACS)
if (( $? != 0 )); then
  print -u2 "mk-src $XEMACS failed"
  exit 1
fi

cd $source_dir
./configure ${=CFG_OPTS} >& conf.out
if (( $? != 0 )); then
  print -u2 "configure failed; see $PWD/conf.out"
  exit 1
fi

make >& mk.out
if (( $? != 0 )); then
  print -u2 "make failed; see $PWD/mk.out"
  exit 1
fi

make check >& check.out

# Local Variables:
# mode: shell-script
# sh-indentation: 2
# indent-tabs-mode: nil
# End:
