#!/usr/bin/env zsh
emulate -LR zsh

# Run conky.
cd ~

# Display the hostname at the center top of the display.
conky --config =(cpp -P .conky.hostname) &

# Optionally display status info on the top right corner.
[[ -z "$KDE_FULL_SESSION" ]] && conky --config =(cpp -P .conky.status) &

# Local Variables:
# mode: shell-script
# sh-basic-offset: 2
# sh-indentation: 2
# indent-tabs-mode: nil
# End:
