#!/usr/bin/env zsh

# Print the number of files under the current directory
# newer than the specified file

emulate -LR zsh
new_files=( $(find_newer $1) )
print ${#new_files}

# Local Variables:
# mode: shell-script
# sh-indentation: 2
# indent-tabs-mode: nil
# End:
