#!/usr/bin/env zsh

# Update rust and build the projects which depend on it.

emulate -LR zsh
progname=${0:t}

usage()
{
}

zparseopts -D h=help

if [[ -n $help ]]; then
  usage
  exit 0
fi
if (( $# == 0 )); then
  usage
  exit 1
fi

# Update the rust compiler.
rustup update stable

# Remove the registry.
rm -rf ~/.cargo/registry

# Rebuild all the commands which are built with rust.
mk-exa --snapshot --install --force
mk-ripgrep --snapshot --install --force

# Local Variables:
# mode: shell-script
# sh-indentation: 2
# indent-tabs-mode: nil
# End:
