#!/bin/bash

# Connect via VNC to the specified server.
PATH=/home/acs/bin:/usr/bin

if (( $# > 0 )); then
  server=$1
  shift
else
  echo -n "Enter server name: "
  read server
fi

if ! ping -c1 -W1 $server >/dev/null ; then
  wakeserver $server
  echo "Please wait while this script starts $server \
and then make sure you complete the login process."
  sleep 30
  vncviewer $server
else
  # Start an ssh tunnel.
  if (( $# > 0 )); then
    local_port=$1
  else
    echo -n "Enter local port number: "
    read local_port
  fi
  ssh -f -L ${local_port}:localhost:5900 ${server} sleep 10
  vncviewer localhost:${local_port}
fi

# Local Variables:
# mode: shell-script
# sh-basic-offset: 2
# sh-indentation: 2
# indent-tabs-mode: nil
# End:
