#!/bin/bash

# Connect a secure shell tunnel and run VNC through it.

server=${1:-nuc}
local_port=${2:-5900}

ssh -N -L ${local_port}:localhost:5900 ${server} &
sleep 1
vncviewer -Fullscreen -menuKey Pause localhost:${local_port}

# Local Variables:
# mode: shell-script
# sh-basic-offset: 2
# sh-indentation: 2
# indent-tabs-mode: nil
# End:
