#!/bin/bash

# If the SUSE package manager exists, echo its name
# and the options necessary to make it non-interactive.
: ${suse_pm=/usr/bin/zypper}
[[ -x $suse_pm ]] && echo $suse_pm --non-interactive

# Local Variables:
# mode: shell-script
# sh-basic-offset: 2
# sh-indentation: 2
# indent-tabs-mode: nil
# End:
