#!/bin/bash

# Toggle sleep state between enabled and disabled.

PATH=$(dirname $0):/usr/bin

# If sleeping is currently enabled, disable it.
if (( $(gnome_sleep_status) != 0 )); then
  gnome_sleep_status 0

# Sleeping is disabled, so enable it.
else

  # Default period of inactivity before sleeping is ten minutes,
  # but it can be overridden by an input parameter.  
  gnome_sleep_status ${1:-600}
fi

# Local Variables:
# mode: shell-script
# sh-indentation: 2
# indent-tabs-mode: nil
# End:
