#!/bin/sh
#
# Unpack a tarball into the source directory.
#
# Usage: unpack generic_package_name
 
# Execute this script under the Z shell
[ ! -n "$ZSH_VERSION" ] && exec zsh "$0" ${1+"$@"}

progname=${0:t}

err=1
if [[ $# -ne 1 ]]; then
  print -u2 "Usage: $progname <pkg>"
  print -u2 "\tpkg is a stripped package name, like \"gcc\" or \"make\"."
  exit $err
fi
pkgbase=$1

((err=err+1))
if ! pushd $SRCROOT >& /dev/null; then
  print -u2 The root of the source hierarchy, $SRCROOT, does not exist.
  exit $err
fi

((err=err+1))
pkgname=$(findpkg $pkgbase)
# Error already reported
if [[ $? -ne 0 ]]; then
  exit $err
fi

((err=err+1))
uncompress=
case $pkgname in
(*.bz2)
  uncompress=bunzip2
  ;;

(*.gz|*.tgz)
  uncompress=gunzip
  ;;

(*)
  case $(file $pkgname) in
  (* bzip2 *)
    uncompress=bunzip2
    ;;

  (* gzip *)
    uncompress=gunzip
    ;;
  esac
esac

if [[ -z "$uncompress" ]]; then
  print -u2 File type of $pkgname is unknown.
  exit $err
fi

$uncompress <$pkgname | tar xf -

# Print the package name before leaving
#print $PWD/${${${pkgname/*$pkgbase/$pkgbase}%.tar*}%.tgz}
print $PWD/${${${pkgname:t}%.tar*}%.tgz}
