#!/usr/bin/env zsh

emulate -LR zsh

for ver in 21.4 21.5; do
  update_and_build xemacs-$ver mk-xemacs -odm $ver $*
done

update_and_build xemacs-packages mk-xp -v $(installed_packages)

# Local Variables:
# mode: ksh
# sh-indentation: 2
# indent-tabs-mode: nil
# End:
