#!/bin/sh

# Execute this script under the Z shell
# The zsh environment will be set up by .zshenv
[ ! -n "$ZSH_VERSION" ] && exec zsh "$0" ${1+"$@"}

roots=cvsupdate
#CVS_RSH=ssh update_and_build emacs mk-emacs $*
update_and_build emacs mk-emacs $*
