#!/usr/bin/env zsh

# Update the CVS sources of zsh and if anything has changed, build them.

emulate -LR zsh

CFLAGS=-O update_and_build zsh mk-zsh $*

# Local Variables:
# mode: shell-script
# sh-indentation: 2
# indent-tabs-mode: nil
# End:

