#!/usr/bin/env zsh

#: ${LOCAL_CYGWIN:=$HOME/Windows/CygwinKit}
: ${LOCAL_CYGWIN:=/opt/CygwinKit}
: ${LOCAL_BIN:=$LOCAL_CYGWIN/bin}
: ${CYGWIN_SETUP_DIR:=http://www.cygwin.com}
: ${RSYNC_SERVER:=rsync://mirrors.kernel.org/sourceware/cygwin/}

emulate -LR zsh
progname=${0:t}

usage()
{
  print -u2 "\
usage: $progname [-h] [-q] [-v]
         -h - print this help message
         -q - run wget and rsync quietly
         -v - run wget and rsync verbosely"
  return 0
}

zparseopts -D h=help q=quiet v=verbose
[[ -n $help ]] && usage && exit 0
[[ -n $quiet ]] && quiet="--quiet"
[[ -n $verbose ]] && verbose="--verbose"

# Nowadays, I just use rsync to keep a complete mirror, but I used to
# copy the repo based on the setup list and remove the extra files.
# That approach saved space at the cost of significant time every time
# the update command was run.
# cd $LOCAL_CYGWIN
# ./bin/clone_repo
# ./bin/clean_cygwin_repo -n

for platform in x86 x86_64; do
  wget $quiet $verbose --output-document=${LOCAL_BIN}/setup-${platform}.exe ${CYGWIN_SETUP_DIR}/setup-${platform}.exe
done
rsync $quiet $verbose -vaz --delete ${RSYNC_SERVER} ${LOCAL_CYGWIN}/cygwin_repo

# Local Variables:
# mode: shell-script
# sh-indentation: 2
# indent-tabs-mode: nil
# End:
