#!/usr/bin/env zsh

emulate -LR zsh

# If the repository is local, rsync from the master site before 'cvs update'
local root=$(< ~/cvsroot/xemacs-21.4/CVS/Root)
case $root in
(*:pserver:*)
  ;;
(*)
  #rsync -qavz --delete --exclude=CVSROOT/config sunsite.dk::xemacscvs $root
  rsync-xemacs
  ;;
esac

for ver in 21.4 21.5; do
  update_and_build xemacs-$ver mk-xemacs -odm $ver $*
done

#update_and_build xemacs-21.4 mk-xemacs -odm $* 21.4
#update_and_build xemacs-21.5 mk-xemacs-21.5 -odm $* 21.5

update_and_build xemacs-packages mk-xp -sv $(installed_packages)

# Local Variables:
# mode: ksh
# sh-indentation: 2
# indent-tabs-mode: nil
# End:
