#!/usr/bin/env zsh

# Wake up the legolas or nuc server from its powernap.

emulate -LR zsh
progname=${0:t}

# Depends on the wakeonlan package:
# sudo apt-get install wakeonlan
# IPV4_address Hostname	MAC
# 192.168.0.4  legolas	BC:5F:F4:8B:7C:A5
# 192.168.0.5  nuc      B8:AE:ED:79:33:98

typeset -A macs
macs[legolas]="BC:5F:F4:8B:7C:A5"
macs[nuc]="B8:AE:ED:79:33:98"

[[ -z "$1" ]] && set legolas
if [[ -z "$macs[$1]" ]]; then
  print -u2 "Usage: $progname [legolas|nuc]"
  exit 1
fi

wakeonlan $macs[$1]

# Local Variables:
# mode: shell-script
# sh-indentation: 2
# indent-tabs-mode: nil
# End:
