#!/bin/bash

# Script to start up an XFCE session.

: ${USRLOCAL:=/opt}
PATH=$HOME/bin:$USRLOCAL/bin:$PATH

# sleep 5
# compton -b

sleep 2
my_conky

tilda &
emacs -f about-emacs &

$HOME/firefoxDE/firefox &
#google-chrome-beta &
#clementine &

# Local Variables:
# mode: shell-script
# sh-basic-offset: 2
# sh-indentation: 2
# indent-tabs-mode: nil
# End:
