#!/bin/bash

# Script to start up an XFCE session.

: ${USRLOCAL:=/opt}
PATH=$HOME/bin:$USRLOCAL/bin:$PATH

xfce4-terminal &
emacs -f about-emacs &

#google-chrome-beta &
#clementine &

conky --pause=15 &

# Local Variables:
# mode: shell-script
# sh-basic-offset: 2
# sh-indentation: 2
# indent-tabs-mode: nil
# End:
