#!/bin/bash

# Script to start up an XFCE session.

: ${USRLOCAL:=/opt}
PATH=$HOME/bin:$USRLOCAL/bin:$PATH

sleep 2
tilda &
emacs -f about-emacs &

$HOME/firefoxDE/firefox &
#google-chrome-beta &
#clementine &

#conky --pause=5 &
sleep 20    # Time to get the fullscreen display set up.
conky --alignment=top_middle \
  --text='${color tomato}${font Comic Sans MS:bold:size=30}${nodename -s}' &
conky &

# Local Variables:
# mode: shell-script
# sh-basic-offset: 2
# sh-indentation: 2
# indent-tabs-mode: nil
# End:
